name: Flutter CI

on:
  push:
    branches: [ "feature/backend-overhaul", "main" ] #change later to main
  pull_request:
    branches: [ "main" ] #change later to main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./attendly

    steps:
      - uses: actions/checkout@v4

      # 1. Use the official Flutter action instead of Dart
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 2. Use 'flutter pub get' instead of 'dart pub get'
      - name: Install dependencies
        run: flutter pub get

      # # 3. Use 'flutter analyze' instead of 'dart analyze'
      # - name: Analyze project source
      #   run: flutter analyze

      # 4. Use 'flutter test' instead of 'dart test'
      - name: Run tests
        run: flutter test
